logging:
  config: classpath:logback.xml

spring:
  profiles:
    active: dev

  jpa:
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 1719

  servlet:
    context-path: /OrchestratorAPI

  error:
    include-stacktrace: never

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha

---

spring:
  config:
    activate:
      on-profile: test

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

---

spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: false